version: "3.9"
services:
  hurricane-info-noaa:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - username=${HURRINFO_USER}
        - uid=1000
        - gid=100
#    command: '/bin/bash'
    volumes:
        - type: bind
          source: /home/ec2-user/data/test/hurricanes
          target:  /home/${HURRINFO_USER}/app/io/output
