version: "3.9"
services:
  pyschism-noaa:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - username=${PYSCHISM_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/mesh
          target:  /home/${PYSCHISM_USER}/app/io/input/mesh
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/coops_ssh
          target:  /home/${PYSCHISM_USER}/app/io/input/coops_ssh
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/setup
          target:  /home/${PYSCHISM_USER}/app/io/output
        - type: bind
          source: /home/ec2-user/data/test/static/tpxo
          target: /home/${PYSCHISM_USER}/.local/share/tpxo
        - type: bind
          source: /home/ec2-user/data/test/static/nwm
          target: /home/${PYSCHISM_USER}/.local/share/pyschism/nwm
          
