version: "3.9"
services:
  hurricane-info-noaa:
    build:
      context: ../info
      dockerfile: docker/Dockerfile
      args:
        - username=${ONDEMAND_USER}
        - uid=1000
        - gid=100
#    command: '/bin/bash'
    command: ${HURRICANE_NAME} ${HURRICANE_YEAR}
    volumes:
        - type: bind
          source: ${OUT_DIR}
          target:  /home/${ONDEMAND_USER}/app/io/output

  ocsmesh-noaa:
#    depends_on:
#        - hurricane-info-noaa
    build:
      context: ../ocsmesh
      dockerfile: docker/Dockerfile
      args:
        - username=${ONDEMAND_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: ${OUT_DIR}
          target:  /home/${ONDEMAND_USER}/app/io/hurricanes
        - type: bind
          source: ${SHAPE_DIR}
          target:  /home/${ONDEMAND_USER}/app/io/shape
        - type: bind
          source: ${DEM_DIR}
          target:  /home/${ONDEMAND_USER}/app/io/dem

  pyschism-noaa:
#    depends_on:
#        - ocsmesh-noaa
#        - hurricane-info-noaa
    build:
      context: ../pyschism
      dockerfile: docker/Dockerfile
      args:
        - username=${ONDEMAND_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: ${OUT_DIR}
          target:  /home/${ONDEMAND_USER}/app/io/hurricanes
        - type: bind
          source: ${TPXO_DIR}
          target: /home/${ONDEMAND_USER}/.local/share/tpxo
        - type: bind
          source: ${NWM_DIR}
          target: /home/${ONDEMAND_USER}/.local/share/nwm
          
  schism-noaa:
#    depends_on:
#        - pyschism-noaa
#        - ocsmesh-noaa
#        - hurricane-info-noaa
    environment:
      - SCHISM_NPROCS=${SCHISM_NPROCS}
    cap_add:
      - SYS_PTRACE
    build:
      context: ../schism
      dockerfile: docker/Dockerfile
      args:
        - username=${ONDEMAND_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: ${OUT_DIR}
          target: /home/${ONDEMAND_USER}/app/io/hurricanes
  odssm-post-noaa:
#    depends_on:
#        - pyschism-noaa
#        - ocsmesh-noaa
#        - hurricane-info-noaa
#        - schism-noaa
    build:
      context: ../post
      dockerfile: docker/Dockerfile
      args:
        - username=${ONDEMAND_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: ${OUT_DIR}
          target: /home/${ONDEMAND_USER}/app/io/hurricanes
