version: "3.9"
services:
  ocsmesh-noaa:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - username=${GEOMESH_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/windswath
          target:  /home/${GEOMESH_USER}/app/io/input/hurricane
        - type: bind
          source: /home/ec2-user/data/test/static/shape
          target:  /home/${GEOMESH_USER}/app/io/input/shape
        - type: bind
          source: /home/ec2-user/data/dem/gebco
          target:  /home/${GEOMESH_USER}/app/io/input/dem/GEBCO
        - type: bind
          source: /home/ec2-user/data/dem/ncei19
          target:  /home/${GEOMESH_USER}/app/io/input/dem/NCEI19
        - type: bind
          source: /home/ec2-user/data/dem/ncei19/tileindex_NCEI_ninth_Topobathy_2014.zip
          target:  /home/${GEOMESH_USER}/app/io/input/dem/tileindex_NCEI_ninth_Topobathy_2014.zip
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/mesh
          target:  /home/${GEOMESH_USER}/app/io/output
