name: icogsc
channels:
  - conda-forge
dependencies:
  - python<3.10
  - pip
  - gdal
  - geos
  - proj
  - netcdf4
  - hdf5
  - cartopy
  - cfunits
  - cf-python
  - cfgrib
  - cmocean
  - esmf
  - esmpy
  - cfdm
  - udunits2
  - pyproj
  - shapely>=2
  - rasterio
  - fiona
  - geopandas>=0.11.0
  - rtree
  - pandas
  - utm
  - scipy
  - numpy
  - matplotlib
  - requests
  - tqdm
  - mpi4py
  - pyarrow
  - pytz
  - geoalchemy2
  - seawater
  - xarray==2023.7.0
  - pip:
    - chaospy>=4.2.7
