name: icogsc
channels:
  - conda-forge
dependencies:
  - python<3.11
  - gdal
  - geos
  - proj
  - netcdf4
  - udunits2
  - pyproj
  - shapely
  - rasterio
  - fiona
  - pygeos
  - geopandas
  - utm
  - scipy
  - numba
  - numpy>=1.21
  - matplotlib
  - requests
  - tqdm
  - mpi4py
  - pyarrow
  - pytz
  - geoalchemy2
  - colored-traceback
  - typing-extensions
