---

- block:
  - name: Add EPEL repo (Ansible prerequisite)
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/

  - name: Install default packages
    yum:
      name:
        - yum-utils
        - tmux
        - htop
        - "@Development tools"
        - python-devel
      state: present

  - name: Install Ansible
    yum:
      name: ansible
      state: present

  - name: Install pip
    yum:
      name:
        - python-pip
      state: present

  - name: Install pip packages for Docker + Ansible
    pip:
      name:
        - docker==4.4.4
        - docker-compose==1.26.2
        - pyrsistent==0.16.1
        - requests==2.25.1
        - websocket-client==0.32.0

  - name: Add Docker repo
    yum_repository:
      name: Docker
      description: Docker Repo
      skip_if_unavailable: yes
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present

  - name: Start Docker
    ansible.builtin.systemd:
      name: docker
      state: started

  - name: Run Thalassa
    docker_container:
      name: "thalassa-{{ deploy_env }}"
      image: "{{ thalassa_image }}:{{ thalassa_image_version }}"
      state: started
      restart: yes
      restart_policy: unless-stopped
      pull: true
      ports: "{{ thalassa_exposed_port }}:{{ thalassa_internal_port }}"
      volumes:
        - "{{ thalassa_data_mnt }}:/data"
        - "{{ thalassa_corral_mnt }}:/data/corral"
      command: "thalassa serve --websocket-origin '*' --port {{ thalassa_internal_port }} --no-show"

  become: true
  tags:
    - deploy
