---

- block:
  - name: Provision micro instance on EC2
    ec2:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      key_name: "{{ prefect_agent_ec2_key }}"
      instance_type: t2.micro
      image: "{{ prefect_agent_image_type }}"
      wait: yes
      count: 1
      region: "{{ prefect_agent_region }}"
      assign_public_ip: yes
      id: odssm-ec2-prefect-agent

  tags:
    - provision