version: "3.9"
services:
  schism-noaa:
    environment:
      - SCHISM_NPROCS=${SCHISM_NPROCS}
    cap_add:
      - SYS_PTRACE
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - username=${SCHISM_USER}
        - uid=1000
        - gid=100
#    command: '/bin/sh'
    volumes:
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/setup/schism.dir
          target: /home/${SCHISM_USER}/app/io/input/
        - type: bind
          source: /home/ec2-user/data/test/hurricanes/florence_2018/sim
          target: /home/${SCHISM_USER}/app/io/output/
